### ISSUE TITLE
Split search API into channels and claims ? 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#109]
The way search works right now, it will return the top X claims and channels based on a search query. This could lead to issues finding channels if the claim results "overwhelm" the channel ones. One example is searching for `Lunduke`. Since he has Lunduke in title names, you only get a bunch of claim results, and nothing on the Channel side.  If I increase the search result #s, I eventually get the channel (tried it at 300).

**Comment by seanyesmunt** [comment]
I think one set of 2x results split equally (or at least make sure there is no less than 1 channel if one exists or something) would work best.

**Comment by kauffj** [comment]
Rather than modifying the signature and behavior of generic search `(/search?s=<term>`), maybe these should just be distinct calls?

If the app wants to display `n` file results and `n` channel results, it may make sense to just make two distinct calls with different parameters/signatures.

**Comment by kauffj** [comment]
My comment may still be unclear. Rather than either splitting the response signature of `search` or _replacing_ search with two new calls, I'm suggesting simply _adding_ two new calls (or a new parameter to `search`) and leaving `search` called as-is with the same behavior.

**Comment by kauffj** [comment]
I think adding a `claim_type=<channel|file>` would be a sensible design.

**Comment by tiger5226** [comment]
Yeah, I agree. 2 calls is best with the claim_type parameter which defaults to all if not passed. 

@seanyesmunt Does this make sense to you?

**Comment by seanyesmunt** [comment]
@tiger5226 A little late to this, but yes.

**Comment by tiger5226** [comment]
merged and deployed with #144
