### ISSUE TITLE
Add param for "no nsfw results" on search api

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lighthouse#110]
For related content, we don't want nsfw results if the user is hiding nsfw content. Currently we just strip out nsfw results app side but this results in some videos with only a few related pieces of content.

It would be nice if there was a new param which makes it so no nsfw results are returned.

**Comment by alyssaoc** [comment]
@tiger5226 Why did this go back to triage?

**Comment by tiger5226** [comment]
I have no reason. I don't recall. Maybe I selected the wrong dropdown when removing my assignment. Cool with groomed.

**Comment by tiger5226** [comment]
The PR for this is complete. However, our documentation needs to be updated. @filipnyquist could you update the docs or add to the readme how this should be done? When we change the API, it would be nice if we keep the docs up to date.

**Comment by filipnyquist** [comment]
https://github.com/lbryio/lighthouse/blob/master/server/routes/lighthouse.js contains the API documentation as in-line swagger doc. When that has been updated you can generate the new API docs with `npm run gendocs` which will handle everything for the documentation.

**Comment by filipnyquist** [comment]
If you want i can get a PR which updates the documentation after we merge the other PR

**Comment by filipnyquist** [comment]
I can take a look on auto-deploying after next week, it´s an exam week so I'm quite full until after it

**Comment by filipnyquist** [comment]
The initial PR and a docs update PR has been merged!

**Comment by filipnyquist** [comment]
This is now live in production!
