### ISSUE TITLE
Exclude blocked content from search results

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lighthouse#12]
List of blocked outpoints is at api.lbry.io/file/list_blocked

**Comment by filipnyquist** [comment]
@lyoshenka , what is the output of endpoints?

**Comment by lyoshenka** [comment]
Its a list of `outpoints`. An outpoint uniquely identifies a file. Its a combination of txid and nout of the publish for the file. It has the form `txid:nout`. For example, the outpoint for the current winning claim on `one` is `8e5d6945d238e8508520364d5eae7885b0db15d77d6d5cffee3f860dc13f0b45:0`

**Comment by kauffj** [comment]
If possible, I would like lighthouse to return the quantity of blocked URLs (and possibly the list itself).

**Comment by filipnyquist** [comment]
Yup, this is tested and now live on production! Closing this issue!
