### ISSUE TITLE
Normalization Hardfork - Changes required

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lighthouse#138]
This line needs to incorporate the returned name field: https://github.com/lbryio/lighthouse/blob/cb7151fa99997c6c376e8d28a4591611221ff226/server/utils/importer/index.js#L82

And a few lines below that, the use of the 'name' field will need to change to the 'normalized_name' field.

**Comment by tiger5226** [comment]
This section of code can be removed. Lighthouse no communicates with lbrycrd. It uses Chainquery. See below:

https://github.com/lbryio/lighthouse/blob/965746b9d26d6461424efbc1efb0e287fc2975bc/server/utils/chainquery/index.js#L158-L184

**Comment by tiger5226** [comment]
Based on the latest information, the following will need to happen to support the hardfork:

- [ ] Elasticsearch needs to store the normalized name of claims for proper search comparisons. 
- [ ] We need to implement NFD Normalization for all search queries that come into the Search and AutoComplete API's The strings stored in elasticsearch will be normalized and we should search based on normalized strings.

**Comment by tiger5226** [comment]
So I found this additional information. https://www.elastic.co/guide/en/elasticsearch/guide/current/unicode-normalization.html

We can add a custom icu analyzer for the name and channel names. I think we need to rebuild the database again with the right collation. @nikooo777. This would also modify the generate db script to ensure the right analyzer is used from the start. Also we should make sure these two fields are normalized to a lowercase name for better comparison.

**Comment by tiger5226** [comment]
So I did some more research here. 

The standard analyzer defaults to treating all strings as unicode strings. They do have an `icu_analyzer` which is what I was referencing above. I originally understood that to mean that we had to apply that analyzer to our index. However, I was wrong. The reason they have this analyzer if incase you want to apply a custom token filter or character filter. These do not expressly handle unicode so you have to specify the `icu_analyzer`. 

The form chosen by the standard analyzer doesn't really matter as we need to only make sure all comparisons are done in the same form. Elasticsearch makes sure these are done in the same form for indexed tokens and query text. 

So we can safely close this issue for lighthouse.
