### ISSUE TITLE
Add weight based on channel effective amount

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#139]
Currently, we add weight to claims based on their claim effective amounts - we should do something similar for channel effective amounts. This would ensure that channels with larger bids rank higher. I may have a large bid on my channel, but only smaller bids on each of my publishes. Think this would help in the case of searching for "Jordan B Peterson" - right now none of his channel's videos show up. The other solution to that is to allow a channel search, but that would bring up his channel, and not claims.

**Comment by tiger5226** [comment]
This is for all claims. Identity and Stream claims. The impact for the weight has been lowered significantly. I suspect that is the issue here.

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lighthouse/blob/fa18e29a8a94c20c1cd9b792aff498cbbb54d7aa/server/controllers/lighthouse.js#L63 shows an effective amount..it's either the claim or the certificate one...how could it be both?

**Comment by tiger5226** [comment]
certificate_amount is the channel claim's effective_amount. I have adjusted to add weight for this and created a PR.

**Comment by tiger5226** [comment]
merged and deployed
