### ISSUE TITLE
The Chainquery sync needs to be done in batches

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lighthouse#142]
Right now, the sync if starting from scratch will grab all claims from chainquery. This transfers a huge amount of data. From recent events this will crash lighthouse with the volume of claims we currently have in the chain. There are a few PRs right that require a full resync of the claims. So this needs to be done first. 

As part of the process, we need to do a full sync on another machine @nikooo777 and then move DNS to that new machine when completed, but only after this batch processing is completed.

**Comment by kauffj** [comment]
Should lighthouse just be using it's own independent chainquery instance?

**Comment by tzarebczan** [comment]
That might be a good idea, but it's not what's causing the initial sync issue Mark mentioned here.

**Comment by tiger5226** [comment]
I added a batching process to only grab 5000 claims at a time. This should make things much easier on node and allow @nikooo777 to continue to rebuild the lighthouse machine so we can merge the other PR too. Solved with 81986315cb98d5ad44b937eb41fe904d1ca0e36b.
