### ISSUE TITLE
Search for `linux gamer` doesn't return @TheLinuxGamer

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#157]
searching `linuxgamer` / `thelinuxgamer` does

We should probably start searching channel titles/description with the new metadata too

**Comment by tiger5226** [comment]
It looks like elasticsearch has a feature we can leverage called [Word Delimiter Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/analysis-word-delimiter-tokenfilter.html). 

[this](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/analysis-asciifolding-tokenfilter.html) appears to be an example of how to set it for a different filter but looks applicable.

**Comment by tiger5226** [comment]
I was able to fix this via adding sub queries that check the concatenation of search terms. So `Linux Gamer` becomes: `Linux`, `Gamer`, and `LinuxGamer`. This is now properly found as a substring for the channel name. 

It ranks 37 now with https://lighthouse.lbry.com/search?s=Linux%20Gamer&size=50
