### ISSUE TITLE
Prepare lighthouse for app integration.

### ISSUE THREAD

**Issue by wallermadev** [lbryio/lighthouse#16]
search currently seems to work as it should and im starting to make the final changes for it to be `lbry-app` ready ideally i would like `lbry-app` to have minimal to no changes to be able to connect to lighthouse to make this happen the following needs to be done.

Required changes to lighthouse;
- [ ] Updating to `post`  as so it matches the prexisting call.

- [x]  Altering the response to only return `name` `claimId` `value`

Nice to haves features to add;
- [ ] add `getClaimsInBlock`
- [ ] add `getSuggestedClaims`
- [ ] add `getTotalClaimsValue`
- [ ] Adding claim statistics calls.

**Comment by wallermadev** [comment]
Response has be updated to only return `name` `claimId` and  `value`

**Comment by kauffj** [comment]
@wallermadev it didn't need to match the old signature. I'd prefer we just pick a right/good signature.

I believe @hackrush already has app-side code changes to use what was on the search server currently.

**Comment by filipnyquist** [comment]
Closing this for now.
