### ISSUE TITLE
"world war two" search doesn't return @worldwartwo

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#161]
"world war two" search doesn't return @worldwartwo

**Comment by tiger5226** [comment]
We can fix this by adding a subquery that removes spaces, so it searches for "worldwartwo" as well.

**Comment by tzarebczan** [comment]
Same for "games glitches" doesn't return @gamesglitches

**Comment by tzarebczan** [comment]
Please fix soon if you can, this is pretty bad.

**Comment by kauffj** [comment]
I think it makes sense to build the script/tool/utility that runs this against all known channels rather than fixing cases one at a time. Then we can tune search algo til it succeeds in 99+% of all known cases.
