### ISSUE TITLE
Add better error handling and logging!

### ISSUE THREAD

**Issue by filipnyquist** [lbryio/lighthouse#26]
Add better error handling and logging sowe know when something goes wrong!

**Comment by tiger5226** [comment]
@filipnyquist Can you please elaborate on this? Like what errors do thing should be handled better and what your suggestion for logging is.

**Comment by filipnyquist** [comment]
I think that logging the errors appering to a logfile with the help of winston would be a inprovment as we easier could check on errors. I´ll see if i can get winston updated to the latest version and also add logfiles for errors.
