### ISSUE TITLE
Search result does not match the pattern requested

### ISSUE THREAD

**Issue by lbry-boost** [lbryio/lighthouse#27]
Example: https://lighthouse.lbry.com/search?s=pwl&claimType=channel
Actual Result:
```
[
  {
    "claimId": "a17cfb382fba460f5c60d7333508585add095f2e",
    "name": "@AlphaOmega"
  }
]
```
"pwl" is not in a channel name.
Expected result: Result should be either empty or contain some channels with "pwl" as a substring

**Comment by tzarebczan** [comment]
Thank you for opening the issue! The search also checks the title and description of the content/channel - can you check to see if there are any matches there?

**Comment by lbry-boost** [comment]
Just checked: indeed there is "pwl" substring in the description. I'll close the issue. Thanks!
