### ISSUE TITLE
lighthouse.lbry.io should redirect to github repo

### ISSUE THREAD

**Issue by kauffj** [lbryio/lighthouse#27]

**Comment by filipnyquist** [comment]
@lyoshenka should it be the normal thing for the / route?

**Comment by lyoshenka** [comment]
not sure what you mean. We want this so when ppl go to lighthouse.lbry.io, they see something useful.

**Comment by filipnyquist** [comment]
I´ll get it to redir to the github page in the next version.

**Comment by filipnyquist** [comment]
@lyoshenka this is now fixed

**Comment by lyoshenka** [comment]
Awesome. ​Please deploy it :-)
