### ISSUE TITLE
Add param to filter out claims without thumbnails

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#3]
Similar to the NSFW param request ( https://github.com/lbryio/lighthouse/issues/110), but this time to filter out claims that don't have a thumbnail.

This came in as a user request and can see it being a valid feature - many users won't click on a claim if a thumbnail doesn't exist. What's tricky here is that a thumb may exist, but won't be valid - maybe these can be filtered on the app side eventually.

**Comment by tiger5226** [comment]
closing since we now have lower weighting for claims without a thumbnail
