### ISSUE TITLE
searching with lbry://xxxxx fails, bad request

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#30]
I just copy/pasted this url:lbry://ee-8blgmbXfDEc into search and I noticed a bad request return in the network logs - the top result is the exactly URL, but at the bottom you see:
```
Search Results for lbry://ee-8blgmbXfDEc ?

lbry://ee-8blgmbXfDEc Be the first
```

I can see users copy/pasting URLs and running into this issue if they don't click Enter immediately.

**Comment by kauffj** [comment]
This will be fixed app side in next release.

**Comment by wilsonk** [comment]
This appears to be fixed in 0.17, I think. Can you confirm @tzarebczan? Maybe close?

**Comment by tzarebczan** [comment]
Yep it is. I had a small comment in the PR maybe to remove LBRY:// (uppercase) too or make the check case insensitive.

**Comment by kauffj** [comment]
Fixed case sensitivity
