### ISSUE TITLE
searching nintendo does not bring up all results

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#33]
Searching for "nintendo" does not bring up lbry://re2-lA-q8DMm5r8#8e1e8b42451a0c0dc3db4e8b4f645f2ad802e665 which has "Nintendo Hardware and Revisitation - Rerez Talks" as the title.

**Comment by wallermadev** [comment]
Will take a look at this as soon as possible,

Dev instance i have seems to return different results will take a look at implementation.

**Comment by tiger5226** [comment]
This has been corrected with the latest release of chain query
The following search will return it as the #1 result.
https://lighthouse.lbry.io/search?s=Nintendo%20Hardware%20and%20Revisitation
