### ISSUE TITLE
searching "retro games" brings back irrelevant results / searching with quotes 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#34]
See below for results searching "retro games". This may be a more general issue when searching with quotes 
![quotes](https://user-images.githubusercontent.com/8120721/31460314-029e642e-ae94-11e7-9b02-6435c6ebeb6a.PNG)

**Comment by tiger5226** [comment]
This has now been corrected with the latest deployment of lighthouse. Quotes are no longer necessary. Searching for phrases will now correctly weight the importance of those words appearing together bringing them to the top of the list. 

https://lighthouse.lbry.io/search?s=Retro%20Games
