### ISSUE TITLE
Return all claims for a search term and not only from winning claim.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lighthouse#36]
If I search for `one` it should show all the claims not only the winning claim. That's how content which is not winning could be discovered. I remember bringing it up earlier, but I forgot what was the verdict on it.

Additional input from @tzarebczan and @kauffj..?

Might be related to #32.

**Comment by kauffj** [comment]
This is correct. All standing and valid claims should be searched. Being
the winning claim can be a weight.

**Comment by filipnyquist** [comment]
I think we pull everything from the claimtrie(just resolvable and standing claims) as of now, as doing it the other way contained a lot of problems (from our internal meeting), we prob would need to write a big function to grab us all claims that can currently be resolved(old claims aswell?), this needs some thinking.

**Comment by filipnyquist** [comment]
Talked with jack and tom on slack and we should be able to get the claimtrie and then use getclaimsforname for all claims in claimtrie, this would give us all claims resolvable.

**Comment by filipnyquist** [comment]
This will be fixed in the upcoming release of the big update to lighthouse which will index the whole chain and resolve this error.

**Comment by tiger5226** [comment]
This is already corrected with the search updates to lighthouse. It will now show results for all claims not just controlling claims. In a future update with ChainQuery we will be able to also search expired claims too.
