### ISSUE TITLE
claim counts, sub counts, and view counts

### ISSUE THREAD

**Issue by kauffj** [lbryio/lighthouse#37]
Most directly prompted by Silvano and the correct The Truth in 11 Minutes not being found. Both have more views, more staked LBC, etc.

#5 and #36 could be part of it

**Comment by kauffj** [comment]
@julianchandra please add examples of searches that are unsatisfactory to this ticket

**Comment by kauffj** [comment]
From Corbett report:

> Search is always tricky, but I note that a search of “Corbett” doesn’t come up with any of my content until the 10th result, and even then, it’s somewhat buried and is only a single video. I realize that my channel name is technically “corbettreport” but realistically no one is going to search that precise string to find my work. As a creator, I’d expect search to reflect keywords and the most obvious human interpretations of channel names and for the channel itself to make it into the search results. (The channel description is “The Corbett Report Official LBRY Channel” so a “Corbett” search could/should return the channel, right?)

**Comment by lbry-boost** [comment]
Here is my train of thoughts around concept of search in LBRY:
1. There is some good questions to debate on: What is a good search? What is the metric to measure quality of search and to optimize for? Without going into huge formalization, I would assume that search is a weighting system on top of text search capability to prioritize outcome based on "likelihood to be useful for an end user" with no bias included.
2. You've already built-in at the very minimum two weighting systems in the app: "Top" and "Trending" (which are proxies for usefulness)
3. The questions becomes if a third system needs to be built for Search function or the ones already developed should be used

    a. If "Top"/"Trending" weighting systems added to accompany search function, then the problem is likely to be smoothed out to certain degree. Empty channels will likely disappear in both categories, plus highly likely Corbett's videos will bubble up higher on the list. If not, then there is someone with a heavy stake of LBC and probably there is a good reason for that. At the end of the day "Corbett" search line should find videos about "Corbett" from others equally well. Disadvantage (or not?) is that search is widely impacted by LBCs at stake.

    b. Implementing Search with a third type of weighting system (probably, it already has its own weighting system different from "Top" and "Trending") may be a good option as long as you let people use "top"/"trending" weighting systems over the outcome as they are quite deterministic with the outcome. Priorities for title over description text matches may be changed, but people will catch up and change the way they name channels/videos. Anyone can go and create five channels with "The Corbett Report Official LBRY Channel” name, there seem to be no way to exclude them from search without applying some sort of bias and start defining where is original channel. This is SEO game where open source nature of the project may not help.

**Comment by kauffj** [comment]
@lbry-boost ack'ing your comment

**Comment by kauffj** [comment]
From a user:
I know that the channel eevblog has a video about "lbry vs youtube" that I wanted to rewatch. Typing "eevblog lbry vs youtube" in search doesn't yield the desired video. One would have to enter the channel's page and use the tiny search bar. The main issue was that the title of the video used "eevblab" instead of "eevblog", but one would expect the search bar to be smart enough to combine the channel name and claim title.

**Comment by kauffj** [comment]
@tiger5226 is going to explore ways to get view and sub data in

**Comment by kauffj** [comment]
Resolve issues with multiple competing complains

**Comment by kauffj** [comment]
Targets this week are claim counts, sub counts, view counts, and winning bid boost (instead of obliteration).

**Comment by tiger5226** [comment]
split out #38 (winning bid boost)

**Comment by tiger5226** [comment]
Its live and syncing the last one `view_counts`
