### ISSUE TITLE
searching for "aquarium" does not return correct result

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#38]
I'd expect this to return: lbry://lobstersr#057bbbff837c8c108dc6b5a8af20bcb3ab8ad31b

**Comment by filipnyquist** [comment]
This should be fixed in the upcoming update to lighthouse, which will include full blockchain coverage and everything else needed to search the whole chain.

**Comment by lyoshenka** [comment]
@filipnyquist is this fixed?

**Comment by tiger5226** [comment]
@tzarebczan Is this issue still open? I still can't find it, but is this because it's waiting for chainquery? @filipnyquist references the "whole blockchain" so I wanted to clarify.

**Comment by tiger5226** [comment]
lbry://lobstersr#057bbbff837c8c108dc6b5a8af20bcb3ab8ad31b

This is not a proper claim reference, so it is no longer reproducible. I strongly believe this is no longer a problem with the latest version of Lighthouse to be deployed. I will close this issue until another scenario can be provided.
