### ISSUE TITLE
Lessen bid amount weight

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lighthouse#4]
When making a search for `"LBRY is quickly gaining adoption"` (to fetch related content), which resides at `lbry://five`, the first result is `lbry://two`, which is `"Mary Jane- Her First Time Doing Porn 33 min"` and is not related at all.

This porn result comes in higher than the actual claim for this file because of it's high bid amount.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
I think this can be closed as there's nothing clearly workable here and the issue is no longer reproducible (video with this title doesn't exist).
