### ISSUE TITLE
Cannot connect to non-local cluster without editing code

### ISSUE THREAD

**Issue by BelfordZ** [lbryio/lighthouse#43]
We should make the elasticsearch config something that can be modified by setting env or config.

**Comment by tiger5226** [comment]
It would be nice if we could use Kibana locally with the production/development elastic search db. Is this what you are referring to?

**Comment by filipnyquist** [comment]
It seems like we should add either a config file or allow the use of env settings so we can override the elastic search db connection details. This would improve the debug experience aswell.

**Comment by filipnyquist** [comment]
Solved with #84

**Comment by tiger5226** [comment]
this is solved but not deployed yet.

**Comment by BelfordZ** [comment]
Thanks guys, awesome work
