### ISSUE TITLE
no results with claim type = channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#44]
https://lighthouse.lbry.com/search?s=trump&size=100&from=0&claimType=channel

**Comment by lbry-boost** [comment]
A few more examples that give empty result: 

https://lighthouse.lbry.com/search?s=nerdrat&claimType=channel
https://lighthouse.lbry.com/search?s=@%E5%86%B7%E6%B7%A1%E7%86%8A&claimType=channel

Even when I remove claimType and set size to 100 channels do not appear in the result. However, they do appear when resolve=true is added and claimType is removed. Like this:

https://lighthouse.lbry.com/search?s=nerdrat&resolve=true
