### ISSUE TITLE
autocomplete is producing errors on production

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lighthouse#56]
Try the following query:

https://lighthouse.lbry.io/autocomplete?s=fillerino

A query should not cause an internal server error.

**Comment by tiger5226** [comment]
The internal server error was because we were checking for a null value for a claim. This is already checked and should never be null. The intention is to make sure we can get the right information out which is only available in a stream. However, there is no stream for channel claims, only certificates. So the fix is to check for null on the stream not the value.

**Comment by filipnyquist** [comment]
As @tiger5226 said this is now fixed. Closing for now!
