### ISSUE TITLE
Irrelevant results

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lighthouse#57]
While searching for "Simpsons," the search result included this video and I can't find any mention of the search term:

lbry://acl-0dLJ2uwkSXI#a1b5f77ced4dcc042478ca2d32c7de14d6c3c524

**Comment by tiger5226** [comment]
If you look closely at the description of the claim you will notice:


> http://www.facebook.com/AcousticLabs.Music - An open tuned (slightly darker) version of Mason Williams' groundbreaking instrumental guitar epic, which I first heard on an early episode of The **Simpsons**.

While the claim maybe is not really relevant, it is doing exactly what is expected.

**Comment by tzarebczan** [comment]
👍 @tiger5226 !!
