### ISSUE TITLE
Return more than 10 search results

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#64]
Lighthouse currently results 10 results, what do we need to do to increase this number? https://lighthouse.lbry.io/search?s=bitcoin

We need to make sure that the app can support more than 10 results by paginating: https://github.com/lbryio/lbry-app/issues/1261

**Comment by tiger5226** [comment]
These changes are now live. Test cases for api below.

```
https://lighthouse.lbry.io/search?s=test&size=100
https://lighthouse.lbry.io/search?s=test&size=1&from=0
https://lighthouse.lbry.io/search?s=test&size=1&from=1
https://lighthouse.lbry.io/search?s=test&size=1&from=2
```
