### ISSUE TITLE
Searching "Danielo" does not return @Danielo channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#66]
This channel was created on spee.ch recently a user noticed that he wasn't able to search for it in the app.

**Comment by tiger5226** [comment]
It shows up as the top search result for me. See screenshot below.

<img width="1042" alt="screen shot 2018-04-29 at 7 29 01 pm" src="https://user-images.githubusercontent.com/3402064/39412032-a14e7be4-4be3-11e8-8e0f-eb1ab6d816c4.png">

**Comment by tzarebczan** [comment]
Yea most likely a timing issue. I'll close once we have a better idea on how it normally takes.

**Comment by filipnyquist** [comment]
It should sync the chain every ten minutes, set by this variable:
https://github.com/lbryio/lighthouse/blob/master/server/utils/importer/index.js#L145

(It also takes 2-3 minutes to get the chain and compare to the old one
before inserting new claims)

Den mån 30 apr. 2018 15:36Thomas Zarebczan <notifications@github.com> skrev:

**Comment by tiger5226** [comment]
I agree, a timing issue is the only explanation. I wanted to post these screenshots just in case something else was awry. If everyone agrees we can close this issue.
