### ISSUE TITLE
if sync fails it never runs again

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lighthouse#69]
The sync process should continue to try on schedule, even if it hits an error. In the current state, if it hits an error the only way to launch the sync process again is restart the lighthouse service on the machine.

This issue is triggered by the investigation of #68. The claim trie had not been synced since the last deployment because it failed once when elastic search connection was not instantly available. Making sure it can retry later, is important to avoiding this in the future.

**Comment by tiger5226** [comment]
This is solved with PR #70.

It the catch of the rejected promise, we should wait the same time interval and try again.

@filipnyquist - Please let me know if you see any issue with this.

**Comment by filipnyquist** [comment]
Pull now merged!
