### ISSUE TITLE
Add ability to search for files and channels, and also include file filters

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lighthouse#8]
It would be really helpful to be able to search for "bitcoin" and request channels, _and only_ audio files.

Right now, if a `mediaType` is included, no channels are included in results.

**Comment by kauffj** [comment]
@seanyesmunt, @tiger5226 thinks this is complete. Can you audit existing functionality to confirm what you'd expect/want is possible?

**Comment by kauffj** [comment]
Re-open if things are missing with details.
