### ISSUE TITLE
Add channel parameter to search api

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lighthouse#90]
This will be to support searching within a specific channel for the app.

**Comment by filipnyquist** [comment]
This sounds like something that would be awesome to have implanted in the app soon! I´ll see if i can get this sorted!

**Comment by tiger5226** [comment]
The API adjustment should be pretty straightforward, the query is usually the bear. https://www.elastic.co/guide/en/elasticsearch/guide/master/combining-filters.html#bool-filter W should use a bool filter. Right now the search query leverages the must and should parts of a bool query. We should be able to dynamically adjust the query to insert the filter part based on the channel parameter being non-blank.

**Comment by tiger5226** [comment]
We will need to get additional information into elastic search. Specifically the name of a channel for a claim so we can easily filter this out. The query to Chainquery needs to be adjusted:
```SQL
SELECT c.name,p.name as channel,c.bid_state,c.effective_amount,c.claim_id as claimId,c.value_as_json as value
FROM claim c
LEFT JOIN claim p on p.claim_id = c.publisher_id
WHERE c.modified >='2018-01-01 00:00:00'
```
This will bring in the new information. In order to get all this sync'd up we just need to adjust the sync state json file to be for 2015 for example so that it resyncs all the claims in the DB. This takes about 45 minutes to fully complete and be searcheable.

**Comment by filipnyquist** [comment]
Fixed with #94

**Comment by tiger5226** [comment]
Keep the issue open until deployed, or mark it as deployed when closing.

**Comment by tiger5226** [comment]
Yeah, but for lighthouse, we don't have auto deployment like internal-apis. Master doesn't mean deployed and we don't have releases, so its how I keep track right now.

**Comment by tiger5226** [comment]
Thinking more we should add that to the next sprint...auto deployment and releases. It can be a bit of work, but from experience it has already saved me tons of time on chainquery.

**Comment by tiger5226** [comment]
https://github.com/lbryio/lighthouse/issues/95
