### ISSUE TITLE
breaking change from Chainquery

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lighthouse#93]
The query used to update the claims will no longer work when https://github.com/lbryio/chainquery/pull/39 is deployed. The change needed is minor `modified` will change to `modified_at`.

**Comment by filipnyquist** [comment]
This change needs to happen at the same time as Chainquery gets updated, I´ve made a PR with the fix( #99 ), @tiger5226 merge it and deploy at the same time as you deploy chainquery #93.

**Comment by tiger5226** [comment]
merged and deployed
