### ISSUE TITLE
Auto-deploy/release lighthouse

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lighthouse#95]
https://github.com/semantic-release/semantic-release

This is a really cool and popular package. Then we just need to process the github webhook when a tagged release is created to download, unzip and startup the binary. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tiger5226** [comment]
I bit the bullet and got this done saturday. #127 is the PR. Once approved the following needs to happen.

1 - The update.sh file needs to be move to the prod environment and needs `chmod 775` so lighthouse can execute it. 
2 - An initial deployment of the changes needs to be done. 
3 - `SLACK_HOOK_URL` environment variable needs to be applied to the prod environment ( I have this ). 
4 - The `travis.yml` needs a commit that sets the production url for the notification. 

The PR does a few things, it allows for a CI/CD workflow on the master branch. The CI is minimal and we can add more checks as we go. For CD there is a new `autoupdate` api. If it is not a PR, is the master branch and is signed by travis, it will run the update script which goes through the current manual deployment process. It also adds slack integration so we can see this workflow happening and can verify it was successful. With the addition of slack integration we will also be able to see any importer errors, or other app errors that need to be addressed.

**Comment by alyssaoc** [comment]
@tiger5226 Can this issue be closed?

**Comment by tiger5226** [comment]
Yes it can be.
