### ISSUE TITLE
Change the API doc to swagger instead of jsdoc.

### ISSUE THREAD

**Issue by filipnyquist** [lbryio/lighthouse#97]
The documentation should be changed to swagger, which will make us follow the OpenAPI spec.
This will make it easier for people to make API clients and give them a better overview of the API.
The code for this is close to ready, it needs some final fixing and swagger checks.

**Comment by kauffj** [comment]
@NetOperatorWibby please consider how we want this displayed on lbry.tech. The primary emphasis on the Resources page will be on the Whitepaper and blockchain/daemon APIs, but secondary APIs such as lighthouse will be displayed there as well.

In the abstract, I'm in favor of using the OpenAPI spec when the API being documented is RESTful.
